### ISSUE TITLE
提交一个bug

### ISSUE THREAD

**Issue by AngusFu** [lvming6816077/H5lock#1]
测试发现，把密码设成图1，图2也能解开。。。

![qq](https://cloud.githubusercontent.com/assets/8180186/8794613/b63766ce-2fb7-11e5-86b1-262a18a96938.png)

![qq 2](https://cloud.githubusercontent.com/assets/8180186/8794618/cdcc3684-2fb7-11e5-91b6-d2047f2613bc.png)

**Comment by lvming6816077** [comment]
已经fix
